version: '3'
services:
  app:
    image: ghcr.io/privatebutts/prusacameraconnect:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/prusacameraconnect/config.yaml:/app/config.yaml
    restart: unless-stopped
